name: Test Automation Workflow

on:
  schedule:
  - cron: 30 13 * * *
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Running Test Automation Framework with Maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false

    - name: Upload Test logs
      if: always()
      uses: actions/upload-artifact@v4.6.1
      with:
        name: Test logs
        path: logs/
    
    - name: Upload Screenshots
      if: always()
      uses: actions/upload-artifact@v4.6.1
      with:
        name: Screenshots
        path: screenshots/

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4.6.1
      with:
        name: Test Reports
        path: report.html

    - name: Test Execution Status
      run: echo "Test Execution Completed" 

    - name: Copy report to public folder
      if: always()
      run: |
        mkdir -p public/extent-reports
        cp -R report.html  public/extent-reports/
        cp -R screenshots/ public/extent-reports/screenshots/
        ls -l

    - name: Deploy
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public/extent-reports/
        token: ${{ secrets.PATTEST }}
        clean: true

      
    
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
